
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: potionstore_development
  username: potionstore
  password: potionstore

production:
  <<: *default
  database: potionstore
  username: potionstore
  password: potionstore

test:
  <<: *default
  database: potionstore_test
  username: pstest
  password: pstest
